services:
    php:
        build: .
        image: php-apache:latest
        container_name: generate-json-app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./public:/var/www/html
        links:
            - db

    db:
        image: mysql:latest
        container_name: generate-json-db
        ports:
            - '3306:3306'
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - MYSQL_DATABASE=banco
