// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteTutorial(arg1:string):Promise<string>;

export function GetAllTutorials():Promise<Array<main.Tutorial>>;

export function InsertTutorial(arg1:main.Tutorial,arg2:Array<number>):Promise<string>;
