// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTutorial(arg1) {
  return window['go']['main']['App']['DeleteTutorial'](arg1);
}

export function GetAllTutorials() {
  return window['go']['main']['App']['GetAllTutorials']();
}

export function InsertTutorial(arg1) {
  return window['go']['main']['App']['InsertTutorial'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}
