// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteContent(arg1, arg2) {
  return window['go']['main']['App']['DeleteContent'](arg1, arg2);
}

export function DeleteTutorial(arg1) {
  return window['go']['main']['App']['DeleteTutorial'](arg1);
}

export function GetAllContents(arg1) {
  return window['go']['main']['App']['GetAllContents'](arg1);
}

export function GetAllTutorials() {
  return window['go']['main']['App']['GetAllTutorials']();
}

export function InsertContent(arg1, arg2) {
  return window['go']['main']['App']['InsertContent'](arg1, arg2);
}

export function InsertTutorial(arg1, arg2) {
  return window['go']['main']['App']['InsertTutorial'](arg1, arg2);
}

export function SendGit(arg1) {
  return window['go']['main']['App']['SendGit'](arg1);
}

export function UpdateContent(arg1, arg2) {
  return window['go']['main']['App']['UpdateContent'](arg1, arg2);
}

export function UpdateTutorial(arg1, arg2) {
  return window['go']['main']['App']['UpdateTutorial'](arg1, arg2);
}
