// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllTutorials():Promise<Array<main.Tutorial>>;

export function Greet(arg1:string):Promise<string>;

export function InsertTutorial(arg1:main.Tutorial):Promise<string>;

export function SaveImage(arg1:string,arg2:Array<number>):Promise<boolean>;
